name: Quarkiverse Pre Release

on:
  pull_request:
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reclaim-disk-space:
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim disk space
        working-directory: .github
        shell: bash
        run: scripts/ci-reclaim-disk-space.sh

  pre-release:
    name: Pre-Release
    needs: reclaim-disk-space
    uses: quarkiverse/.github/.github/workflows/pre-release.yml@main
    secrets: inherit
